---
environment: production
chdir: /var/www/wedding
address: 127.0.0.1
user: root
group: root
port: 4567
pid: /var/www/wedding/thin.pid
log: /var/www/wedding/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
servers: 2
